# Generated by Django 6.0.3 on 2026-04-17 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AILegal', '0004_case_document_alter_advicehistory_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConstitutionArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_number', models.CharField(db_index=True, max_length=30, unique=True)),
                ('title', models.CharField(max_length=500)),
                ('part', models.CharField(max_length=200)),
                ('part_number', models.CharField(max_length=10)),
                ('tags', models.JSONField(default=list)),
                ('short_description', models.TextField()),
                ('full_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'constitution_articles',
                'ordering': ['id'],
            },
        ),
    ]
