import os
import tempfile
import uuid
from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas
from reportlab.lib.utils import simpleSplit

def generate_advice_pdf(document_type: str, content: dict) -> str:
    """
    Generates a PDF using reportlab to specific path.
    Returns path to temporary PDF file.
    """
    temp_dir = tempfile.gettempdir()
    filename = f"{uuid.uuid4().hex}_{document_type.replace(' ', '_')}.pdf"
    filepath = os.path.join(temp_dir, filename)
    
    c = canvas.Canvas(filepath, pagesize=letter)
    width, height = letter
    
    # Header
    c.setFont("Helvetica-Bold", 16)
    c.drawString(50, height - 50, "AI Legal Assistant")
    c.setFont("Helvetica", 10)
    c.drawString(50, height - 65, "Generated Legal Report")
    
    c.setStrokeColorRGB(0.1, 0.3, 0.8) # #1d4ed8 Blue Accent 
    c.line(50, height - 75, width - 50, height - 75)
    
    # Title
    c.setFont("Helvetica-Bold", 14)
    c.drawString(50, height - 100, str(document_type).upper())
    
    # Content Body
    c.setFont("Helvetica", 11)
    y = height - 130
    
    # Render basic key-value data nicely
    for key, value in content.items():
        if key == 'ai_drafted_body': continue # Skip AI draft from PDF
        
        c.setFont("Helvetica-Bold", 11)
        label = str(key).replace('_', ' ').title() + ":"
        c.drawString(50, y, label)
        y -= 15
        
        c.setFont("Helvetica", 11)
        # Handle lists or strings
        if isinstance(value, list):
            for item in value:
                lines = simpleSplit(f"• {item}", "Helvetica", 11, width - 100)
                for line in lines:
                    c.drawString(60, y, line)
                    y -= 15
        else:
            lines = simpleSplit(str(value), "Helvetica", 11, width - 100)
            for line in lines:
                c.drawString(50, y, line)
                y -= 15
                
        y -= 10 # spacing after section
        
        if y < 100: # New page logic
            c.showPage()
            y = height - 50

    # Footer
    c.setFont("Helvetica-Oblique", 9)
    c.drawString(50, 30, "Generated by AI Legal Assistant — For informational purposes only")
    
    c.save()
    return filepath
